import type { DesignResumeDocument, PdfRenderer } from "@shared/types";
import { PDF_RENDERER_LABELS } from "@shared/types";
import { Eye } from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { DesignResumePdfPreview } from "./DesignResumePdfPreview";

type DesignResumePreviewPanelProps = {
  draft: DesignResumeDocument;
  pdfRenderer: PdfRenderer;
  isUpdatingRenderer: boolean;
  isDirty: boolean;
  saveState: "idle" | "saving" | "saved" | "error";
  onPdfRendererChange: (renderer: PdfRenderer) => void;
};

export function DesignResumePreviewPanel({
  draft,
  pdfRenderer,
  isUpdatingRenderer,
  isDirty,
  saveState,
  onPdfRendererChange,
}: DesignResumePreviewPanelProps) {
  return (
    <section className="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-border/70 bg-muted/20">
      <div className="flex flex-wrap items-start justify-between gap-4 border-b border-border/70 px-4 py-4">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
            <Eye className="h-4 w-4" />
            Live preview
          </div>
          <p className="mt-1 text-xs text-muted-foreground">
            This shows the actual PDF generated by the selected template.
          </p>
        </div>

        <div className="grid w-full gap-2 sm:max-w-[17rem]">
          <label
            htmlFor="design-resume-template"
            className="text-[11px] font-medium uppercase tracking-[0.22em] text-muted-foreground"
          >
            Template
          </label>
          <Select
            value={pdfRenderer}
            onValueChange={(value) =>
              onPdfRendererChange(value === "latex" ? "latex" : "rxresume")
            }
            disabled={isUpdatingRenderer}
          >
            <SelectTrigger id="design-resume-template">
              <SelectValue placeholder="Choose a template" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="rxresume">
                {PDF_RENDERER_LABELS.rxresume}
              </SelectItem>
              <SelectItem value="latex">{PDF_RENDERER_LABELS.latex}</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-hidden">
        <DesignResumePdfPreview
          draft={draft}
          pdfRenderer={pdfRenderer}
          isUpdatingRenderer={isUpdatingRenderer}
          isDirty={isDirty}
          saveState={saveState}
        />
      </div>
    </section>
  );
}
